default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Attereco-Back_development

test:
  <<: *default
  database: Attereco-Back_test

production:
  <<: *default
  database: Attereco-Back_production
  username: Attereco-Back
  password: <%= ENV['ATTERECO-BACK_DATABASE_PASSWORD'] %>
